### ISSUE TITLE
SignalR Chat with Redis

### ISSUE THREAD

**Issue by cmthomps** [personball/abplus#17]
Hi - Thanks very much for your work here.  Did you get SignalR chat to work with a Redis server?  I've got your code running and it seems to work when all users are connected to the same web server.  But if the users are connected to different web servers, the users appear to be "offline".   I can see the users registered in the Redis server in the Abplus.RealTime.OnlineClients.Clients and Users.  So I'm not entirely sure what the issue is.  It seems like Abp maybe defaulting back to using the original Abp Chat functionality.  Any help would be appreciated.

Thanks again,
Craig

**Comment by personball** [comment]
@cmthomps  Do you set the backplane of signalr?

Please see: https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr

**Comment by cmthomps** [comment]
Thanks, I finally got it all working.  My problem was getting the dependency injection configured correctly.  I really do appreciate your work on this.  Seems like something they should build into the base.

**Comment by personball** [comment]
@cmthomps  You are welcome.
