### ISSUE TITLE
Rebus程序集注册问题

### ISSUE THREAD

**Issue by virtualcca** [personball/abplus#18]
问什么不通过Castle的程序集注册Convention的模式扫描IHandleMessage接口直接注册队列处理程序，反而要额外指定程序集的形式去获取？  直接通过程序集注册感觉集成度更高也减少使用方面的交互（不然觉得为什么塞个程序集进去莫名其妙，就感觉集成度很低）

**Comment by personball** [comment]
@virtualcca  因为一直追求的是非侵入式扩展，而rebus本身也是一个比较完整的框架，从集成度上讲反而不希望两者过于紧密。当初是以Abp的模块的形式做了一次“桥接”，利用了rebus良好的MQ抽象，以避免在Abp这边重新进行MQ相关的抽象。最后，说实话一直对Castle不够了解，水平有限，如果有更自然的集成方式，欢迎PR，谢谢关注。
