### ISSUE TITLE
请问如何在单个进程中托管多个Rebus实例

### ISSUE THREAD

**Issue by cunzhu** [personball/abplus#20]
您好作者，我觉得你应该是位中国的大神，所以就没有将问题翻译成英文，毕竟我的英语也很歪。我在使用你的插件时，遇到这个错误：
InvalidOperationException: An IBus service is already registered in this container. If you want to host multiple Rebus instances in a single process, please use separate container instances for them.

事情的起因是我在我的项目里面使用了队列，队列的发布端在展现层的控制器里面，订阅端在应用层里面，也就是发布端和订阅端都在同一个项目里面，然后就报这个错了，把订阅端的代码注释了就好了，请问一下怎么实现，在单个进程中托管多个Rebus实例

其实这个错误很明显，但是菜的一笔的我，不知道怎么解决，希望能得到您的帮助

**Comment by personball** [comment]
@cunzhu  直接使用消费端模块即可，无需使用发布端。在abplus对接rebus的两个模块中，发布模块使用的是单向连接方式，消费端使用的是双向连接方式，即消费端模块同时支持发布和消费。

**Comment by cunzhu** [comment]
大神你好，感谢你在百忙之中抽出宝贵的时间来帮我解答问题，经过测试，我发现将发布者，订阅者还有module的配置都写在MVC层是没有问题的，如果分开写，比如说消费者写应用层（Application），消费者就不再工作，另外全部写在应用层，也是一样的，消费者并不会自动去消费，这是为什么呢？我使用对垒主要是为了支持支付功能，支付有可能发生在PC端，也可能在APP上，如果只能放在同一层，那应该是应用层最合适了，我先贴出的代码（以下代码尽量省去一些无关紧要的逻辑）

`namespace MLCDZ
{
    [DependsOn(typeof(MLCDZCoreModule),typeof(AbpAutoMapperModule), typeof(RebusRabbitMqConsumerModule))]
    public class MLCDZApplicationModule : AbpModule
    {
        public override void PreInitialize()
        {
            #region RabbitMq消费端配置 
            Configuration.Modules.UseAbplusRebusRabbitMqConsumer()
                .UseLogging(c => c.Log4Net())
                .ConnectTo("amqp://admin:123456@127.0.0.1:5672/")//连接
                .UseQueue("PayQueue")//队列名称
                .Prefetch(100)//用于控制每次拉取的资源消耗(内存,带宽),消费速度还要看消费端自己的消息处理速度
                .SetMaxParallelism(1)//最大并行数
                .SetNumberOfWorkers(10)//设置最大工作线程数
                                       //配置其他选项
                .UseOptions(x => x.SimpleRetryStrategy(maxDeliveryAttempts: 50, secondLevelRetriesEnabled: true, errorTrackingMaxAgeMinutes: 20))
                .RegisterHandlerInAssemblys(Assembly.GetExecutingAssembly());//注册包含Hander的处理程序??
            #endregion RabbitMq消费端配置
        }

        public override void Initialize()
        {
            var thisAssembly = typeof(MLCDZApplicationModule).GetAssembly();

            IocManager.RegisterAssemblyByConvention(thisAssembly);

            Configuration.Modules.AbpAutoMapper().Configurators.Add(
                // Scan the assembly for classes which inherit from AutoMapper.Profile
                //扫描程序集以查找从 AutoMapper.Profile 继承的类
                cfg => cfg.AddProfiles(thisAssembly)
            );
        }

        #region  RabbitMq发布端配置
        public override void PostInitialize()
        {
            //Abp.Dependency.IocManager.Instance.IocContainer.AddFacility<LoggingFacility>(f => f.LogUsing<NLogFactory>().WithConfig("nlog.config"));
            var workManager = IocManager.Resolve<IBackgroundWorkerManager>();
            workManager.Add(IocManager.Resolve<MlcdzBackgroundWorker>());//定义一个后台工作发布信息
        }
        #endregion
    }
}`

`namespace MLCDZ.Application
{
    /// <summary>
    /// 创建后台工作者 https://www.jianshu.com/p/d20027bd76d5
    /// </summary>
    public class MlcdzBackgroundWorker : PeriodicBackgroundWorkerBase, ISingletonDependency
    {
        private readonly IMqMessagePublisher _publisher;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="timer"></param>
        /// <param name="publisher"></param>
        public MlcdzBackgroundWorker(AbpTimer timer, IMqMessagePublisher publisher)
            : base(timer)
        {
            _publisher = publisher;
            Timer.Period = 1 * 1000;//3 seconds 
            Timer.RunOnStart = true;
        }

        /// <summary>
        /// 测试队列发布
        /// </summary>
        protected override void DoWork()
        {
            Logger.Info($"TestWork Done! Time:{DateTime.Now}");
            _publisher.Publish(new TestMessage
            {
                Value = "TestWork from DotNetCoreHost:BlaBlaBlaBlaBlaBla",
                Time = DateTime.Now
            });
        }
    }
}`

`namespace MLCDZ.Application.Svc
{
    /// <summary>
    /// 应用层服务的接口实现方法  
    /// </summary>
    [AbpAuthorize]
   public class BillInfoAppService : MLCDZAppServiceBase, IBillInfoAppService, IHandleMessages<TestMessage>
    {
        private readonly ILogger Logger;
        public IMqMessagePublisher Publisher { get; set; }
        /// <summary>
        /// 构造函数 
        ///</summary>
        public BillInfoAppService()
        {
            //.................. 依赖注入
            Logger = NullLogger.Instance;
            Publisher = NullMqMessagePublisher.Instance;
        }
        
        /// <summary>
        /// 测试队列消费
        /// </summary>
        /// <param name="message"></param>
        /// <returns></returns>
        public async Task Handle(TestMessage message)
        {
            var msg = $"{Logger.GetType()}:{message.Value},{message.Time}";
            Logger.Debug(msg);
            await Publisher.PublishAsync(msg);//send it again!
        }
...................................
`

**Comment by personball** [comment]
.RegisterHandlerInAssemblys(Assembly.GetExecutingAssembly())  

Assembly.GetExecutingAssembly()    

handler在哪个程序集，这个要匹配上

**Comment by cunzhu** [comment]
![image](https://user-images.githubusercontent.com/50855175/71144066-b016ba00-2257-11ea-8d6f-8554b4ddeb12.png)

**Comment by cunzhu** [comment]
我将Assembly.GetExecutingAssembly() 改成了Assembly.Load("MLCDZ.Application")还是不行，按理说3个都在应用层，直接Assembly.GetExecutingAssembly() 获取当前程序集就行了，但是不行，然后我看了一下bin目录下生产的程序集名称是MLCDZ.Application，但是还是不行。另外之前上传的图片得点一下才能显示出来

**Comment by personball** [comment]
@cunzhu RegisterHandlerInAssemblys(Assembly.GetAssembly(typeof(handler的类型或者放handler的程序集中任何一个类)))

**Comment by cunzhu** [comment]
大神，谢谢你的帮助，问题并不是出在获取程序集，而是因为handler写在了XXXAppService中，这个类继承了其他的业务逻辑和接口，导致消费逻辑不能被触发，我像你上面说的那样改了之后，还是不行，然后我将它单独的写在了一个类中，消费逻辑就正常执行了，最后非常感谢您的帮助

**Comment by cunzhu** [comment]
真不好意，我又来了，O(∩_∩)O哈哈~
我在用的时候，发现你的插件似乎没有提供消费后的应答代码呀，是继承并实现IMessageTracker接口吗？可是那两个方法的processId参数从哪里来呢？

**Comment by personball** [comment]
@cunzhu ack机制只要消费的业务逻辑代码没有异常，rebus底层会自动处理。  IMessageTracker 接口用于幂等机制

**Comment by cunzhu** [comment]
确实是有个错误 Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID d4ab63c8-e8d6-4737-8ce5-7b7981576eed and type MLCDZ.Dtos.TestMessage, MLCDZ.Application could not be dispatched to any handlers (and will not be retried under the default fail-fast settings)
不会又是因为我把发布者和消费者放在不同的层中导致的吧

**Comment by senxiaoxing** [comment]
> 确实是有个错误 Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID d4ab63c8-e8d6-4737-8ce5-7b7981576eed and type MLCDZ.Dtos.TestMessage, MLCDZ.Application could not be dispatched to any handlers (and will not be retried under the default fail-fast settings)
> 不会又是因为我把发布者和消费者放在不同的层中导致的吧

我也遇到类似的错误：Rebus.Exceptions.RebusApplicationException: Message with ID knuth-7075567080679998033 and type Newtonsoft.Json.Linq.JObject, Newtonsoft.Json could not be dispatched to any handlers

请问你解决了吗？

**Comment by personball** [comment]
> > 确实是有个错误 Rebus.Exceptions.MessageCouldNotBeDispatchedToAnyHandlersException: Message with ID d4ab63c8-e8d6-4737-8ce5-7b7981576eed and type MLCDZ.Dtos.TestMessage, MLCDZ.Application could not be dispatched to any handlers (and will not be retried under the default fail-fast settings)
> > 不会又是因为我把发布者和消费者放在不同的层中导致的吧
> 
> 我也遇到类似的错误：Rebus.Exceptions.RebusApplicationException: Message with ID knuth-7075567080679998033 and type Newtonsoft.Json.Linq.JObject, Newtonsoft.Json could not be dispatched to any handlers
> 
> 请问你解决了吗？

根据异常提示信息，请排查消费端是否正确包含了该消息的消费handler。
