### ISSUE TITLE
: An IBus service is already registered in this container. If you want to host multiple Rebus instances in a single process, please use separate container instances for them

### ISSUE THREAD

**Issue by lszai90** [personball/abplus#22]
你好，我想请问一下
 我多个生产者、  多个生产责 配置不同的队列名  相对应的有对应的消费者。 但是现在在
_bus = rebusConfig.Transport(c => c.UseRabbitMq(moduleConfig.ConnectString, moduleConfig.QueueName)).Start();
transport第二个队列名称时　提示：An IBus service is already registered in this container. If you want to host multiple Rebus instances in a single process, please use separate container instances for them.

告诉我这个Ｉbus 已经在容器中注册了  我想达到的目的就是不同业务 使用不同队列

**Comment by personball** [comment]
@lszai90  请查看Rebus的具体用法，abplus仅实现了pub/sub模式，你的场景应该是produce/consume模式
