### ISSUE TITLE
我还想问一下错误码设计，就是想替换AjaxResponse这个

### ISSUE THREAD

**Issue by amin168** [personball/abplus#3]
```
{
     code:0
     message:"success"
     result:{}
}
```

如果要改成以上这种，可以在abp什么地方改的，提供的思路就可以了，因为我看见你博客有这个目录，所以想提早问一下这个，谢谢= =

**Comment by personball** [comment]
AjaxResponse是请求封包，这块我并没有试过替换。
ErrorCode的设计主要是错误码枚举+通用业务异常+本地化语言配置错误提示信息，这三者结合以防滥用UserFriendlyException。其中需要自定义ErrorInfoConverter。

**Comment by personball** [comment]
AjaxResponse不建议替换，因为Abp本身框架级机制在AjaxResponse上有体现，如果用了自已新定义的封包，会损失框架现有机制或者导致接口封包不一致。

如果想比较灵活的对外提供webapi，可以不使用动态映射webapi那块的机制，所有webapi都自己包一层ApiController。

**Comment by amin168** [comment]
好的，谢谢你哈

**Comment by personball** [comment]
@amin168 Abp系列——业务异常与错误码设计及提示语的本地化 http://personball.com/abp/2017/08/28/abp-error-code-design

上面说的封包机制是可以关闭的，用` [DontWrapResult]`

**Comment by amin168** [comment]
@personball 嗯，我知道有这种特性`DontWrapResult`，谢谢你哈
